// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQrq0onvqtumq7BSsXEPWgGUhJn-vptw',
    appId: '1:21684444537:web:6daa4f88d14a7fab6d23a8',
    messagingSenderId: '21684444537',
    projectId: 'dsi-2020-2',
    authDomain: 'dsi-2020-2.firebaseapp.com',
    storageBucket: 'dsi-2020-2.firebasestorage.app',
    measurementId: 'G-76B2334ZYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfl4MJQTNY1hL27Z_aEhKROdOzM8NZQqw',
    appId: '1:21684444537:android:c26cca172c0fe7276d23a8',
    messagingSenderId: '21684444537',
    projectId: 'dsi-2020-2',
    storageBucket: 'dsi-2020-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUspkfzAeC9xR6aIAIdLtokMyKv0KU9sE',
    appId: '1:21684444537:ios:695cddd2ab53a01b6d23a8',
    messagingSenderId: '21684444537',
    projectId: 'dsi-2020-2',
    storageBucket: 'dsi-2020-2.firebasestorage.app',
    iosClientId: '21684444537-n5et7b0kss6dcgreljpk55kkvlpmnj3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUspkfzAeC9xR6aIAIdLtokMyKv0KU9sE',
    appId: '1:21684444537:ios:695cddd2ab53a01b6d23a8',
    messagingSenderId: '21684444537',
    projectId: 'dsi-2020-2',
    storageBucket: 'dsi-2020-2.firebasestorage.app',
    iosClientId: '21684444537-n5et7b0kss6dcgreljpk55kkvlpmnj3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQrq0onvqtumq7BSsXEPWgGUhJn-vptw',
    appId: '1:21684444537:web:afe438fa090b31736d23a8',
    messagingSenderId: '21684444537',
    projectId: 'dsi-2020-2',
    authDomain: 'dsi-2020-2.firebaseapp.com',
    storageBucket: 'dsi-2020-2.firebasestorage.app',
    measurementId: 'G-R6LHDQSY4C',
  );
}
